{% set version = "1.8.1" %}

package:
  name: torch
  version: {{ version }}

source:
  git_url: https://github.com/pytorch/pytorch.git
  git_rev: v{{ version }}

requirements:
  build:
    - cmake
    - typing-extensions 3.10.0.0
  host:
    - python
    - chaquopy-libgfortran 4.9  # arm64-v8a uses ld.bfd, which transitively resolves all symbols.
    - chaquopy-openblas 0.2.20
    - numpy 1.17.4
