package:
  name: numpy
  # version: 1.19.5
  # version: 1.17.4
  # Most recent release as of 20221021
  version: 1.23.3
  # Most recent release with universal2 wheels
  # version: 1.22.1

requirements:
  build:
    - Cython 0.29.32
  # host:
  #   - chaquopy-openblas 0.2.20
  #   - chaquopy-libgfortran 4.9  # Required by ld.bfd on arm64 (see build-wheel.py)
