package:
  name: numpy
  # version: 1.19.5
  version: 1.17.4
requirements:
  build:
    - Cython 0.29.24
  # host:
  #   - chaquopy-openblas 0.2.20
  #   - chaquopy-libgfortran 4.9  # Required by ld.bfd on arm64 (see build-wheel.py)
