package:
  name: matplotlib
  version: 3.6.0

build:
  number: 1

requirements:
  host:
    - chaquopy-freetype 2.9.1
    - chaquopy-libpng 1.6.34
    - numpy 1.18.5

# about:
#   license_file: LICENSE/LICENSE
