{% set version = "2.1.0" %}

package:
  name: tensorflow
  version: {{ version }}

build:
  number: 9

source:
  url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz

requirements:
  build:
    - numpy 1.23.3

    # Required by create_python_api.py (version from tensorflow/tools/pip_package/setup.py).
    - keras_preprocessing 1.1.0

  host:
    - python
    - numpy 1.20
