{% set version = "2.5.0" %}

package:
  name: tflite-runtime
  version: {{ version }}

source:
  url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz

requirements:
  host:
    - python
    - numpy 1.23.3
